include: package:lint/analysis_options.yaml

linter:
    rules:
        sort_unnamed_constructors_first: false
        join_return_with_assignment: false

analyzer:
    exclude:
        - "**/*.g.dart"
        - "**/*.freezed.dart"
    errors:
        invalid_annotation_target: ignore