name: dexter_pm_frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  freezed_annotation: ^0.15.0
  http: ^0.13.4
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  lint: ^1.7.2

flutter:
  uses-material-design: true
